### ISSUE TITLE
Advantages over built-in Fronius integration?

### ISSUE THREAD

**Issue by Aerodynamite** [drc38/Fronius_solarweb#21]
Hi, I saw this integration pop up as a new integration available in my HACS store and I was wondering what the advantages are of this versus the built-in [Fronius integration ](https://www.home-assistant.io/integrations/fronius)that I have been using up untill now.

Do you have more sensors available or quicker updates or ...?

Best regards

**Comment by texta83** [comment]
you can i get the api access key id an dapi access key value?

**Comment by drc38** [comment]
It is intended if your Fronius is on a different network to HA, otherwise you are best to use the built-in integration.

**Comment by texta83** [comment]
> > How can i get the api access key id an dapi access key value?
> 
> Details are in the readme link and on Fronius website

There is no api in fronius website.
Api is not for private use, only commercial

**Comment by drc38** [comment]
I asked my local Fronius rep and was granted access as a private user to the api.

**Comment by texta83** [comment]
Please note that regardless of the type of access, the use of the Solar.web Query API is only possible for business partners (corporate customers).

https://www.fronius.com/de/solarweb-query-api/zugang-zur-api
